version: '3.6'
 
services:
  php-fpm:
    build:
      context: ./php-fpm
    user: ${UID}
    env_file:
      - ./.env
    volumes:
      - ../:/var/www
    working_dir: /var/www
    depends_on:
      - composer
      - php-cli-consumer
      - mariadb
    ports:
      - 9001:9000

  php-cli-consumer:
    build:
      context: ./php-cli-consumer
    user: ${UID}
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - ../:/app
    working_dir: /app
    depends_on:
      - composer
      - rabbitmq

  mariadb:
    build:
      context: ./mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
      - ./mariadb/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3307:3306

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/var/www
    depends_on:
      - php-fpm
    ports:
      - 81:80

  rabbitmq:
    build:
      context: ./rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15673"]
        interval: 30s
        timeout: 10s
        retries: 5
    ports:
      - 15673:15672
      - 5673:5672

  redis:
    image: redis:5.0.0-alpine
    ports:
      - 6380:6379

  composer:
    image: composer
    user: ${UID}
    volumes:
      - ../:/app
    command: composer install --ignore-platform-reqs -a -o --prefer-dist

volumes:
  mariadb: